### ISSUE TITLE
Incompatibility with watson-fabric-1.16.2-1.4.4 - LVTGeneratorError: Could not locate method metadata for `addMessage` generating LVT in `net/minecraft/ChatHud`

### ISSUE THREAD

**Issue by iCaitlyn** [Andrews54757/OptiFabric-updated#13]
Watson for 1.16.2 was recently released. On 1.16.1, the previous version of Watson and OptiFabric runs fine together with no crashes.

Attempting to use it with OptiFabric produces the following error:

```
[00:20:20] [main/INFO]: Mod 'watson' uses the modmenu:clientsideOnly custom value unnecessarily, as it can be inferred from the mod's declared environment.
[00:20:20] [main/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[00:20:21] [main/INFO]: Backend library: LWJGL version 3.2.2 build 10
[00:20:23] [main/INFO]: [OptiFine] 
[00:20:23] [main/INFO]: [OptiFine] OptiFine_1.16.2_HD_U_G3_pre4
[00:20:23] [main/INFO]: [OptiFine] Build: 20200825-180551
[00:20:23] [main/INFO]: [OptiFine] OS: Windows 10 (amd64) version 10.0
[00:20:23] [main/INFO]: [OptiFine] Java: 1.8.0_212-3-redhat, Oracle Corporation
[00:20:23] [main/INFO]: [OptiFine] VM: OpenJDK 64-Bit Server VM (mixed mode), 
[00:20:23] [main/INFO]: [OptiFine] LWJGL: 3.3.0 Win32 WGL EGL OSMesa VisualC DLL
[00:20:23] [main/INFO]: [OptiFine] OpenGL: GeForce GTX 1070/PCIe/SSE2, version 4.6.0 NVIDIA 443.09, NVIDIA Corporation
[00:20:23] [main/INFO]: [OptiFine] OpenGL Version: 4.6.0
[00:20:23] [main/INFO]: [OptiFine] Maximum texture size: 32768x32768
[00:20:23] [main/INFO]: [Shaders] OpenGL Version: 4.6.0 NVIDIA 443.09
[00:20:23] [main/INFO]: [Shaders] Vendor:  NVIDIA Corporation
[00:20:23] [main/INFO]: [Shaders] Renderer: GeForce GTX 1070/PCIe/SSE2
[00:20:23] [main/INFO]: [Shaders] Capabilities:  2.0  2.1  3.0  3.2  4.0 
[00:20:23] [main/INFO]: [Shaders] GL_MAX_DRAW_BUFFERS: 8
[00:20:23] [main/INFO]: [Shaders] GL_MAX_COLOR_ATTACHMENTS_EXT: 8
[00:20:23] [main/INFO]: [Shaders] GL_MAX_TEXTURE_IMAGE_UNITS: 32
[00:20:23] [main/INFO]: [Shaders] Load shaders configuration.
[00:20:23] [main/INFO]: [Shaders] Save shaders configuration.
[00:20:23] [VersionCheck/INFO]: [OptiFine] Checking for new version
[00:20:23] [main/INFO]: [Shaders] No shaderpack loaded.
[00:20:24] [VersionCheck/INFO]: [OptiFine] java.io.FileNotFoundException: http://optifine.net/version/1.16.2/HD_U.txt
[00:20:24] [main/INFO]: [STDERR]: org.spongepowered.asm.util.throwables.LVTGeneratorError: Could not locate method metadata for method_1804 generating LVT in net/minecraft/class_338
[00:20:24] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.util.Locals.getLocalsAt(Locals.java:147)
[00:20:24] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.injection.modify.LocalVariableDiscriminator$Context.initLocals(LocalVariableDiscriminator.java:136)
[00:20:24] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.injection.modify.LocalVariableDiscriminator$Context.<init>(LocalVariableDiscriminator.java:130)
[00:20:24] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.injection.modify.ModifyVariableInjector$Context.<init>(ModifyVariableInjector.java:69)
[00:20:24] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.injection.modify.ModifyVariableInjector.inject(ModifyVariableInjector.java:146)
[00:20:24] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:264)
[00:20:24] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:385)
[00:20:24] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1284)
[00:20:24] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
[00:20:24] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
[00:20:24] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[00:20:24] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[00:20:24] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
[00:20:24] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[00:20:24] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
[00:20:24] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
[00:20:24] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
[00:20:24] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
[00:20:24] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
[00:20:24] [main/INFO]: [STDERR]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[00:20:24] [main/INFO]: [STDERR]: 	at net.minecraft.class_329.<init>(class_329.java:157)
[00:20:24] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.<init>(class_310.java:543)
[00:20:24] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:177)
[00:20:24] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:20:24] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[00:20:24] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:20:24] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[00:20:24] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
[00:20:24] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
[00:20:24] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
[00:20:24] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:20:24] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[00:20:24] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:20:24] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[00:20:24] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[00:20:24] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[00:20:24] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[00:20:24] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 8/27/20 12:20 AM
Description: Initializing game

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_329.<init>(class_329.java:157)
	at net.minecraft.class_310.<init>(class_310.java:543)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: org.spongepowered.asm.util.throwables.LVTGeneratorError: Could not locate method metadata for method_1804 generating LVT in net/minecraft/class_338
	at org.spongepowered.asm.util.Locals.getLocalsAt(Locals.java:147)
	at org.spongepowered.asm.mixin.injection.modify.LocalVariableDiscriminator$Context.initLocals(LocalVariableDiscriminator.java:136)
	at org.spongepowered.asm.mixin.injection.modify.LocalVariableDiscriminator$Context.<init>(LocalVariableDiscriminator.java:130)
	at org.spongepowered.asm.mixin.injection.modify.ModifyVariableInjector$Context.<init>(ModifyVariableInjector.java:69)
	at org.spongepowered.asm.mixin.injection.modify.ModifyVariableInjector.inject(ModifyVariableInjector.java:146)
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:264)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:385)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1284)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 24 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_329.<init>(class_329.java:157)
	at net.minecraft.class_310.<init>(class_310.java:543)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.16.2
	Minecraft Version ID: 1.16.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_212-3-redhat, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), 
	Memory: 998977008 bytes (952 MB) / 1386741760 bytes (1322 MB) up to 1908932608 bytes (1820 MB)
	CPUs: 8
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx2048m
	Fabric Mods: 
		fabric: Fabric API 0.19.0+build.398-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474c4e
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea894e
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce533984e
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308364e
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f4e
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea8664e
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d4e
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.0+e2e6cdad4e
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b4e
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.1+91555cd14e
		fabric-item-api-v1: Fabric Item API (v1) 1.1.0+29679fd64e
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f96364e
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c64e
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c54e
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b204e
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+fac8f3664e
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce994e
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d64e
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b4e
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f4e
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.6.0+e81ec80b4e
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+ba4afa574e
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a704e
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.4.3+e5d3217f4e
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb84e
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.4+5d32f5834e
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.1.0+e2862de64e
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d4e
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.10+e5d3217f4e
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104904e
		fabric-rendering-v1: Fabric Rendering (v1) 1.2.0+fc24ff244e
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.9+e5d3217f4e
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+872498414e
		fabric-structure-api-v1: Fabric Structure API (v1) 1.0.0+516ece7c4e
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c594e
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb84e
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.2+ccce563e4e
		fabricloader: Fabric Loader 0.9.2+build.206
		malilib: MaLiLib 0.10.0-dev.21+arne.1
		minecraft: Minecraft 1.16.2
		mm: Manningham Mills 2.0
		modmenu: Mod Menu 1.14.6+build.31
		optifabric: Optifabric 1.1.0-beta2
		org_slf4j_slf4j-api: slf4j-api 1.7.30
		org_slf4j_slf4j-simple: slf4j-simple 1.7.30
		org_zeroturnaround_zt-zip: zt-zip 1.14
		watson: Watson 1.4.4-dev.20200826.205333
```

**Comment by iCaitlyn** [comment]
Disregard, looks like yet another mod incompatability that didn't exist in 1.16.1

**Comment by iCaitlyn** [comment]
Updated title with the mod that proved to be incompatible, after testing of each mod to see which stops OptiFabric + OptiFine from working.

The mod is watson-fabric-1.16.1-1.4.3-dev.20200804.153427.jar, from: https://www.curseforge.com/minecraft/mc-mods/watson

Their Github page is located at: https://github.com/vacla/Watson
Their Discord server (for perhaps improved communication) is at https://discord.gg/VTHVVgt

**Comment by iCaitlyn** [comment]
Sorry, disregard again, misintepreted the message in their announcement (Released Watson 1.16.x 1.4.3) to include 1.16.2, when it only included 1.16.0 and 1.16.1

**Comment by iCaitlyn** [comment]
Issue remains the same even with the latest version of Watson, so reopening it now, sorry.

**Comment by iCaitlyn** [comment]
Watson is now compatible with OptiFabric thanks to changes by the dev and Choco
