### ISSUE TITLE
crash with multiconnect-1.3.15（1.13.16 and 1.13.17）

### ISSUE THREAD

**Issue by WKyouka** [Andrews54757/OptiFabric-updated#15]
The game crashed whilst rendering overlay
Error: java.lang.NoSuchMethodError: net.minecraft.class_1088.getSpriteMap()Lnet/minecraft/class_4724;

**Comment by IMS212** [comment]
I am getting an different error with multiconnect 1.3.14 (game works fine but the game freezes and this error appears if i try to change shaders/textures in game):
`Error executing task on Client
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_268.method_1197()" because "☃" is null
	at net.minecraft.class_269.method_1191(class_269.java:199)
	at net.minecraft.class_634.method_11099(class_634.java:2154)
	at net.minecraft.class_2755.method_11860(class_2755.java:122)
	at net.minecraft.class_2755.method_11054(class_2755.java:16)
	at net.minecraft.class_2600.lambda$checkThreadAndEnqueue$0(class_2600.java:34)
	at net.minecraft.class_1255.method_18859(class_1255.java:172)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:134)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.class_310.method_1523(class_310.java:990)
	at net.minecraft.class_310.method_1514(class_310.java:656)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

**Comment by Andrews54757** [comment]
lol, gotta love the local variable problems with utf8. snowman is null.

**Comment by IMS212** [comment]
yep, ill get a picture one sec (the problem is that it doesnt crash it just freezes, so i dont get a crash report)

**Comment by IMS212** [comment]
https://imgur.com/a/eOAQ99s this is what it looks like in log output.
